[default]

[servo]
pins = [16,19,26,20]
angle_factors = [-1,1,-1,1]  # "mpmp"

[rpc]
proto = "http"
host = "0.0.0.0"
port = 8000
apipath = "/api"

[rpcclnt_bt]
prefix = "ms:.2 st:30"
mr_prefix = "ms:0.3 st:10 mr:"

[rpcclnt_bt.keys]
KEY_S = "ms:1 st:40 mv:0,0,0,0"

[rpcclnt_bt.mr_keys]
KEY_C = [ 5, 0, 0, 0]
KEY_D = [-5, 0, 0, 0]
KEY_E = [0,  5, 0, 0]
KEY_F = [0, -5, 0, 0]
KEY_G = [0, 0,  5, 0]
KEY_I = [0, 0, -5, 0]
KEY_H = [0, 0, 0,  5]
KEY_J = [0, 0, 0, -5]
