[project]
name = "ottopi0"
dynamic = ["version"]
description = "OttoPi3: Otto DIY like biped robot for Raspberry Pi"
readme = "README.md"
license = { file = "LICENSE" }
authors = [
    { name = "Yoichi Tanibayashi", email = "yoichi@tanibayashi.jp" }
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: POSIX :: Linux",
    "Topic :: System :: Hardware",
    "Topic :: System :: Hardware :: Hardware Drivers",
]
requires-python = ">=3.11"
dependencies = [
    "blessed>=1.22.0",
    "click>=8.3.0",
    "dynaconf>=3.2.12",
    "fastapi[standard]>=0.120.2",
    "json-rpc>=1.15.0",
    "uvicorn>=0.38.0",
    "pibtinput",
    "pi0servo",
]

[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "vcs"

[project.scripts]
ottopi0 = "ottopi0.__main__:cli"

[dependency-groups]
dev = [
    "mypy>=1.18.2",
    "pyright>=1.1.406",
    "pytest>=8.4.2",
    "ruff>=0.14.0",
    "pytest-mock>=0.14.0",
]

[tool.ruff.format]
docstring-code-line-length = 78

[tool.ruff.lint.per-file-ignores]
"conftest.py" = ["F401", "F811"]

[[tool.mypy.overrides]]
module = [
    'pigpio',
    'requests',
    'fastapi',
    'fastapi.testclient',
    'uvicorn',
    'jsonrpc',
    'dynaconf',
    'pi0servo',
    'pibtinput',
]
ignore_missing_imports = true
check_untyped_defs = true

[tool.pytest.ini_options]
pythonpath = "tests"

[tool.uv.sources]
pi0servo = { path = "../pi0servo" }
pibtinput = { path = "../pibtinput" }
